function $(i){var e=(typeof i=="string")? document.getElementById(i):i;return{"$":e,"html":function(){return _h([ this.$ ]);},"style":function(p){if(typeof p=="string"){return this.$.style[p];}for(a in p){this.$.style[a]=p[a];}},"attr":function(p){if(typeof p=="string"){return this.$.getAttribute(p);}for(a in p){this.$.setAttribute(a,p[a]);}},"fadeIn":function(n,s){fadeIn(this.$,n,s);},"fadeOut":function(n,s){fadeOut(this.$,n,s);},"class":function(m){if(m==undefined){return this.$.className;}if(bS(this.$.className,m))return this.$.className+=" "+m;},"event":function(e,f){if(f==undefined){e=(bS(e,"on"))? e.substring(2):e;var t=cE(e);this.$.dispatchEvent(t);}else{this.$[e]=f;}}};
};
function $class(m){return{"m":m,"$_":lA(document.getElementsByClassName(m)),"style":function(p){this.$_.forEach(function($){for(a in p){$.style[a]=p[a];}});},"event":function(e,f){this.$_.forEach(function($){$[e]=f;});},"html":function(){return _h(this.$_)}};
};
function $tag(g){return{"g":g,"$_":lA(document.getElementsByTagName(g)),"style":function(p){this.$_.forEach(function($){for(a in p){$.style[a]=p[a];}});},"event":function(e,f){this.$_.forEach(function($){$[e]=f;});},"html":function(){return _h(this.$_)}};
};
function _h($_){return{"$_":$_,"append":function(h){this.$_.forEach(function($){$.innerHTML+=h;});},"replace":function(h){this.$_.forEach(function($){$.innerHTML=h;});},"prepend":function(h){this.$_.forEach(function($){$.innerHTML=h+$.innerHTML;});},"text":function(h){this.$_.forEach(function($){$.innerText=h;});}};
};
function $hash(w){return{"val":(w || w!=undefined)? window.location.hash:window.location.hash.substring(1),"set":function(s){window.location.hash=s;}};
};
function print(s){document.write(s);};
function fadeIn(i,n,s){if(n==undefined){n=1;}if(s==undefined){s=.01;}if($(i).style("opacity")==""){$(i).style({"opacity":0});}$(i).style({"display":""});fI(i.id,n,s);};
function fI(){var i=arguments[0];var n=arguments[1];var s=parseFloat(arguments[2]);var o=parseFloat($(i).style("opacity"));o+=s;$(i).style({"opacity":""+o});if(o<n){if(window[i+"-t"]==null){window[i+"-t" ]=setInterval("fI(\""+i+"\",\""+n+"\",\""+s+"\")",10);}}else{clearInterval(window[i+"-t"]);window[i+"-t"]=null;}};
function fadeOut(i,n,s){if(n==undefined){n=0;}if(s==undefined){s=.01;}if($(i).style("opacity")==""){$(i).style({"opacity":1});}fAO(i,n,s);};
function fO(){var i=arguments[0];var n=arguments[1];var s=parseFloat(arguments[2]);var o=parseFloat($(i).style("opacity"));o-=s;$(i).style({"opacity":""+o});if(o>n){if(window[i+"-t"]==null)window[i+"-t"]=setInterval("fO(\""+i+"\",\""+n+"\",\""+s+"\")",10);}else{clearInterval(window[i+"-t"]);window[i+"-t"]=null;$(i).style({"display":"none"});}};
function mT(e){var t=document.createElement("textarea");t.id=e.id;t.value=e.innerHTML;t.className=e.className;var p=e.parentNode;p.replaceChild(t,e);};
function $ajax(o){var s=(o.type=="GET")? "?":"";for(var i=0;i<o.data.length;i++){s+=o.data[i]+"&";}s=s.substring(0,s.length-1);var x=new XMLHttpRequest();if(o.sync){x.onreadystatechange=function(){if(x.readyState==4 && x.status==200){o.fn(x.responseText);}}}if(o.type=="POST"){x.open(o.type,o.dest,o.sync);x.setRequestHeader("Content-Type","application/x-www-form-urlencoded");x.send(s);}else if(o.type=="GET"){x.open(o.type,o.dest+s,o.sync);x.send();}};
function bS(h,s){if(typeof s=="string")return h.search(s)!=-1;for(var i=0;i<s.length;i++){if(h.search(s[i])!=-1){return true;}}return false;};
function cE(e){var v;var w="init";if(bS(e,["click","mouse"])){v=document.createEvent("MouseEvent");w+="Mouse";}else if(bS(e,"key")){v=document.createEvent("KeyboardEvent");w+="Keyboard";}else if(bS(e,"textInput")){v=document.createEvent("TextEvent");w+="Text";}else if(bS(e,["focus","blur","scroll","resize"])){v=document.createEvent("UIEvent");w+="UI";}w+="Event";v[w](e,true,true,window,0,0,0,0,0,false,false,false,false,0,null);return v;};
function tT(l,f){for(var i=0;i<l.rows.length;i++){for(var j=0;j<l.rows[i].cells.length;j++){f(l.rows[i].cells[j]);}}};
function lA(n){var a=new Array();for(var i=0;i<n.length;i++)a.push(n[i]);return a;};

